// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Message struct {
	ID     int32         `json:"id"`
	Text   string        `json:"text"`
	UserID sql.NullInt32 `json:"user_id"`
	RoomID sql.NullInt32 `json:"room_id"`
}

type Room struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
}

type RoomMember struct {
	UserID int32 `json:"user_id"`
	RoomID int32 `json:"room_id"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
