// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	UserID string `json:"userId"`
	User   *User  `json:"user"`
}

type NewRoom struct {
	Title   string   `json:"title"`
	Members []string `json:"members"`
}

type Room struct {
	ID      string  `json:"id"`
	Title   *string `json:"title"`
	Members []*User `json:"members"`
}

type SendMessageInput struct {
	UserID string `json:"userId"`
	RoomID string `json:"roomId"`
	Text   string `json:"text"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
